name: Documentation

on:
  push:
    branches:
      - master

jobs:
  publish-documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get dependencies
        run: |
          sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
      - name: Generate doxygen documentation
        run: doxygen Doxyfile
      - name: Publish documentaton
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
